config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

#resources :change_deadlines
#post 'change_deadlines/new', :controller => 'change_deadlines', :action => 'create'
match '/change_deadlines/context_menu', :to => 'context_menus#requests', :as => 'requests_context_menu', :via => [:get, :post]
post 'change_deadlines/new', to: 'change_deadlines#create'
patch '/change_deadlines/:id/edit', to: 'change_deadlines#update'
post '/change_deadlines/:id/approve_request', to: 'change_deadlines#approve_request', :as => 'approve_request'
get '/change_deadlines/:id/approve_request', to: 'change_deadlines#approve_request'
post '/change_deadlines/:id/reject_request', to: 'change_deadlines#reject_request', :as => 'reject_request'
get '/change_deadlines/:id/reject_request', to: 'change_deadlines#reject_request'
match '/change_deadlines', :controller => 'change_deadlines', :action => 'destroy', :via => :delete

resources :change_deadlines do
  collection do
    match 'bulk_edit', :via => [:get, :post]
    match 'approve_request', :via => [:get, :post]
    match 'reject_request', :via => [:get, :post]
    post 'bulk_update'
  end
end

app/controllers/change_deadlines_controller.rb
class ChangeDeadlinesController < ApplicationController

  helper :queries
  include QueriesHelper
  include ChangeDeadlinesHelper
  helper :change_deadlines

  before_action :find_request, only: [:edit, :update, :show]
  #before_action :find_request, only: [:edit, :update, :show, :destroy, :approve_request, :reject_request]
  before_action :find_requests, :only => [:bulk_edit, :bulk_update, :destroy, :approve_request, :reject_request]

  def new
    @request = RequestChangeDeadline.new
    @issue_ids = params[:issue_ids]
    @issues = Issue.find @issue_ids
  end

  def create
    new_deadlines = params[:new_deadline]
    issue_ids = []
    new_deadlines.each do |new_deadline|
      issue_ids << new_deadline.first.to_i
    end
    issues = Issue.find issue_ids
    issues.each do |issue|
      @request = RequestChangeDeadline.new
      @request.user_id = User.current.id
      @request.issue_id = issue.id
      @request.project_id = issue.project_id
      @request.new_deadline = params[:new_deadline]["#{issue.id}"]
      @request.reason = params[:reason]["#{issue.id}"]
      @cf_setting = Setting.plugin_redmine_request_change_deadline['custom_field']
      @cfv = issue.custom_values.detect { |cv|
        cv.custom_field_id == @cf_setting.first.to_i
      }
      @request.old_deadline = @cfv.value if @cfv
      @request.save
    end
    redirect_to issues_path
  end

  def index
    retrieve_request_change_deadline_query
    if @query.valid?
      @requests_count = @query.requests_count
      @request_pages = Paginator.new @requests_count, per_page_option, params['page']
      @requests = @query.requests(:offset => @request_pages.offset, :limit => @request_pages.per_page)
    end
  end

  def edit
  end

  def bulk_edit
  end

  def update
    @request.safe_attributes = params_request
    @request.save
    redirect_to change_deadlines_path
  end

  def bulk_update
    @requests.each do |request|
      request.new_deadline = params[:new_deadline]["#{request.issue.id}"]
      request.reason = params[:reason]["#{request.issue.id}"]
      request.save
    end
    redirect_to change_deadlines_path
  end

  def show
  end

  #def destroy
  #  @request.destroy
  #  redirect_to change_deadlines_path
  #end

  def destroy
    @requests.each do |request|
      request.destroy
    end
    redirect_to change_deadlines_path
  end

  #def approve_request
  #  @request.status = 1
  #  @request.approved_by_id = User.current.id
  #  @issue = Issue.find(@request.issue_id)
  #  @cf_setting = Setting.plugin_redmine_request_change_deadline['custom_field']
  #  @cfv = @issue.custom_values.detect { |cv|
  #    cv.custom_field_id == @cf_setting.first.to_i
  #  }
  #  if @cfv
  #    @cfv.value = @request.new_deadline
  #    @cfv.save
  #    @request.save
  #  end
  #  redirect_to change_deadlines_path
  #end

  def approve_request
    @requests.each do |request|
      request.status = 1
      request.approved_by_id = User.current.id
      issue = Issue.find(request.issue_id)
      cf_setting = Setting.plugin_redmine_request_change_deadline['custom_field']
      cfv = issue.custom_values.detect { |cv|
        cv.custom_field_id == cf_setting.first.to_i
      }
      if cfv
        cfv.value = request.new_deadline
        cfv.save
        request.save
      end
    end
    redirect_to change_deadlines_path
  end

  #def reject_request
  #  @request.status = 2
  #  @request.save
  #  redirect_to change_deadlines_path
  #end

  def reject_request
    @requests.each do |request|
      request.status = 2
      request.save
    end
    redirect_to change_deadlines_path
  end

  private

  def new_deadline_params
    params.require(:new_deadline).permit!
  end

  def find_request
    @request = RequestChangeDeadline.find params[:id]
  end

  def find_requests
    @requests = RequestChangeDeadline.
        where(:id => (params[:id] || params[:ids])).to_a
    raise ActiveRecord::RecordNotFound if @requests.empty?
    #@projects = @issues.collect(&:project).compact.uniq
    #@project = @projects.first if @projects.size == 1
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def params_request
    params.require(:request_change_deadline).permit(:reason, :new_deadline)
  end

  def retrieve_request_change_deadline_query
    request_retrieve_query(RequestChangeDeadlineQuery, false, :defaults => @default_columns_names)
  end
  
end

app/helpers/change_deadlines_helper.rb
module ChangeDeadlinesHelper

  include QueriesHelper
  include ApplicationHelper

  def change_deadline_column_content(column, item)
    value = column.value_object(item)
    if value.is_a?(Array)
      values = value.collect {|v| column_value(column, item, v)}.compact
      safe_join(values, ', ')
    else
      change_deadline_column_value(column, item, value)
    end
  end

  def change_deadline_column_value(column, item, value)
    case column.name
    when :id
      link_to value, change_deadline_path(item)
    when :subject
      link_to value, issue_path(item)
    when :parent
      value ? (value.visible? ? link_to_issue(value, :subject => false) : "##{value.id}") : ''
    when :description
      item.description? ? content_tag('div', textilizable(item, :description), :class => "wiki") : ''
    when :last_notes
      item.last_notes.present? ? content_tag('div', textilizable(item, :last_notes), :class => "wiki") : ''
    when :done_ratio
      progress_bar(value)
    when :relations
      content_tag('span',
                  value.to_s(item) {|other| link_to_issue(other, :subject => false, :tracker => false)}.html_safe,
                  :class => value.css_classes_for(item))
    when :hours, :estimated_hours
      format_hours(value)
    when :spent_hours
      link_to_if(value > 0, format_hours(value), project_time_entries_path(item.project, :issue_id => "#{item.id}"))
    when :total_spent_hours
      link_to_if(value > 0, format_hours(value), project_time_entries_path(item.project, :issue_id => "~#{item.id}"))
    when :attachments
      value.to_a.map {|a| format_object(a)}.join(" ").html_safe
    else
      format_object(value)
    end
  end

  def request_retrieve_query(klass, use_session=true, options={})
    session_key = klass.name.underscore.to_sym

    if params[:query_id].present?
      cond = "project_id IS NULL"
      cond << " OR project_id = #{@project.id}" if @project
      @query = klass.where(cond).find(params[:query_id])
      raise ::Unauthorized unless @query.visible?
      @query.project = @project
      session[session_key] = {:id => @query.id, :project_id => @query.project_id} if use_session
    elsif api_request? || params[:set_filter] || !use_session || session[session_key].nil? || session[session_key][:project_id] != (@project ? @project.id : nil)
      # Give it a name, required to be valid
      @query = klass.new(:name => "_", :project => @project)
      @query.build_from_params(params, options[:defaults])
      session[session_key] = {:project_id => @query.project_id, :filters => @query.filters, :group_by => @query.group_by, :column_names => @query.column_names, :totalable_names => @query.totalable_names, :sort => @query.sort_criteria.to_a} if use_session
    else
      # retrieve from session
      @query = nil
      @query = klass.find_by_id(session[session_key][:id]) if session[session_key][:id]
      @query ||= klass.new(:name => "_", :filters => session[session_key][:filters], :group_by => session[session_key][:group_by], :column_names => session[session_key][:column_names], :totalable_names => session[session_key][:totalable_names], :sort_criteria => session[session_key][:sort])
      @query.project = @project
    end
    if params[:sort].present?
      @query.sort_criteria = params[:sort]
      if use_session
        session[session_key] ||= {}
        session[session_key][:sort] = @query.sort_criteria.to_a
      end
    end
    @query
  end

  def grouped_request_list(requests, query, &block)
    ancestors = []
    grouped_query_results(requests, query) do |request, group_name, group_count, group_totals|
      yield request, ancestors.size, group_name, group_count, group_totals
      ancestors << request
    end
  end

  def requests_destroy_confirmation_message(requests)
    requests = [requests] unless requests.is_a?(Array)
    message = "Êtes-vous sûr de vouloir supprimer la ou les demandes(s) selectionnée(s) ?"
  end

  def change_deadline_query_links(queries)
    return '' if queries.empty?
    # links to #index on issues/show
    url_params = controller_name == 'change_deadlines' ? {:controller => 'change_deadlines', :action => 'index', :project_id => @project} : {}
    ul_content_tag = content_tag('ul',
                                 queries.collect {|query|
                                   css = 'query'
                                   css << ' selected' if query == @query
                                   content_tag('li', link_to(query.name, url_params.merge(:query_id => query), :class => css))
                                 }.join("\n").html_safe,
                                 :class => 'queries')
    content_tag(:div, ul_content_tag, class: 'module-content', id: '_user-easyquery_EasyIssueQuery_private')
  end

  def delete_link_query(url, options={})
    options = {
        :method => :delete,
        :data => {:confirm => l(:text_are_you_sure)},
        :class => 'icon icon-del button-negative'
    }.merge(options)

    link_to l(:button_delete), url, options
  end
end

app/views/change_deadlines/_column_query.html.erb
<% tag_name = (options[:name] || 'c') + '[]'%>
<% tag_id = tag_name.gsub(/[\[\]]+/, '_').sub(/_+$/, '') %>
<% available_tag_id = "available_#{tag_id}" %>
<% selected_tag_id = "selected_#{tag_id}" %>

<table class="filters-table">
  <tr class="columns-container" id="columns" style="">
    <td class="columns-heading"><label>Columns</label></td>
    <td><table style="border-collapse: collapse; border:0; width: auto" class="columns">
      <tbody><tr>
        <td style="padding-left:0">
          <%= select_tag 'available_columns',
                         options_for_select(query_available_inline_columns_options(query)),
                         :id => available_tag_id,
                         :multiple => true, :size => 10,
                         :ondblclick => "moveOptions(this.form.#{available_tag_id}, this.form.#{selected_tag_id});" %>
        </td>
        <td style="vertical-align: middle; text-align: center; width: 5%">
          <input type="button" value="&#8594;" class="move-right"
                 onclick="moveOptions(this.form.<%= available_tag_id %>, this.form.<%= selected_tag_id %>);" />
          <input type="button" value="&#8592;" class="move-left"
                 onclick="moveOptions(this.form.<%= selected_tag_id %>, this.form.<%= available_tag_id %>);" />   <td style="width: 45%">
        <%= select_tag tag_name,
                       options_for_select(query_selected_inline_columns_options(query)),
                       :id => selected_tag_id,
                       :multiple => true, :size => 10,
                       :ondblclick => "moveOptions(this.form.#{selected_tag_id}, this.form.#{available_tag_id});" %>
      </td>
        <td style="vertical-align: middle; text-align: center; width: 5%">
          <input type="button" value="&#8648;" onclick="moveOptionTop(this.form.<%= selected_tag_id %>);" />
          <input type="button" value="&#8593;" onclick="moveOptionUp(this.form.<%= selected_tag_id %>);" />
          <input type="button" value="&#8595;" onclick="moveOptionDown(this.form.<%= selected_tag_id %>);" />
          <input type="button" value="&#8650;" onclick="moveOptionBottom(this.form.<%= selected_tag_id %>);" />    </td>
      </tr>
      </tbody></table>
    </td>
  </tr>
  <% if @query.groupable_columns.any? %>
    <tr>
      <td class="field"><label for='group_by'><%= l(:field_group_by) %></label></td>
      <td><%= group_by_column_select_tag(@query) %></td>
    </tr>
  <% end %>
  <% if @query.available_block_columns.any? %>
    <tr>
      <td class="field"><%= l(:button_show) %></td>
      <td><%= available_block_columns_tags(@query) %></td>
    </tr>
  <% end %>
  <% if @query.available_totalable_columns.any? %>
    <tr>
      <td><%= l(:label_total_plural) %></td>
      <td><%= available_totalable_columns_tags(@query) %></td>
    </tr>
  <% end %>
</table>

app/views/change_deadlines/_date_range.html.erb
<% query = @query %>
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'type', @query.type, :disabled => true, :id => 'query_type' %>
<%= query_hidden_sort_tag(@query) %>

<div id="query_form_content" class="easy-query-filter-container with-freetext">
  <div class="easy-query-heading">
    <div class="buttons contextual">
      <div class="filters open" id="easy-query-toggle-button-filters">
        <a href="javascript:void(0);">
          <i class="icon-toggler"></i>Filters<span class="default-filter">default</span></a>
      </div>
      <script type="application/javascript">
          //<![CDATA[
          EasyGem.schedule.late(function(){
              $("#easy-query-toggle-button-filters").bind('click', function(e, el) {
                  EASY.utils.toggleDivAndChangeOpen('filters', "#easy-query-toggle-button-filters");
                  EASY.query.toggleFilterButtons('filter_buttons', '.easy-query-filter-toggle');
              });
          }, 0);
          //]]>
      </script>
      <div class="settings" id="easy-query-toggle-button-settings">
        <a href="javascript:void(0);">
          <i class="icon-toggler"></i>
          Options</a>
      </div>
      <script type="application/javascript">
          //<![CDATA[
          EasyGem.schedule.late(function(){
              $("#easy-query-toggle-button-settings").bind('click', function(e, el) {
                  EASY.utils.toggleDivAndChangeOpen('filters_settings', "#easy-query-toggle-button-settings");
                  EASY.query.toggleFilterButtons('filter_buttons', '.easy-query-filter-toggle');
              });
          }, 0);
          //]]>
      </script>
    </div>
  </div>

  <div class="easy-query-filter-settings">
    <div id="filters" class="easy-query-filter-toggle gray-background filters collapsible" style="display: block;">

      <div id="easyquery-filters" class="easyquery-filters">
        <div class="add-filter tabular">
          <p>
          <div id="query_form_with_buttons" class="hide-when-print">
            <div id="query_form_content">
              <div style="<%= @query.new_record? ? "" : "display: none;" %>">
                <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
              </div>
              </fieldset>
            </div>
          </div>
          </p>
        </div>

      </div>

    </div>
    <div id="filters_settings" class="easy-query-filter-toggle gray-background others collapsible collapsed" style="display: none;">

      <div id="outputs_settings">
        <div class="list_settings output-settigs-box" data-output="list" style="">
          <%= render partial: 'column_query', locals: {query: @query, options: {}} %>
        </div>
      </div>
    </div>
  </div>


  <p id="filter_buttons" class="form-actions filter-buttons" style="display: block;">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked apply-link button-positive' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :sort => '', :project_id => @project }, :class => 'icon icon-reload clear-link button-negative'  %>
    <% if @query.new_record? %>
      <% if User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_type').prop('disabled',false);$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                             :class => "icon icon-save save-link button" %>
      <% end %>
    <% else %>
      <% if @query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_query_path(@query), :class => 'icon icon-edit button-positive' %>
        <%= delete_link_query query_path(@query) %>
      <% end %>
    <% end %>
  </p>

</div>

app/views/change_deadlines/_filters.html.erb
<%= javascript_tag do %>
var operatorLabels = <%= raw_json Query.operators_labels %>;
var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
var availableFilters = <%= raw_json query.available_filters_as_json %>;
var labelDayPlural = <%= raw_json "Days" %>;

var filtersUrl = <%= raw_json queries_filter_path(:project_id => @query.project.try(:id), :type => @query.type) %>;

$(document).ready(function(){
  initFilters();
  <% query.filters.each do |field, options| %>
  addFilter("<%= field %>", <%= raw_json query.operator_for(field) %>, <%= raw_json query.values_for(field) %>);
  <% end %>
});
<% end %>

<table id="filters-table">
</table>

<div class="add-filter">
<%= label_tag('add_filter_select', "Add filter") %>
<%= select_tag 'add_filter_select', filters_options_for_select(query), :name => nil %>
</div>

<%= hidden_field_tag 'f[]', '' %>
<% include_calendar_headers_tags %>

app/views/change_deadlines/_form.html.erb
<%= f.label :reason, 'Reason of request' %>
<%= f.text_field :reason %><br>
<%= f.label :new_deadline, 'New deadline' %>
<%= f.date_field :new_deadline %><br>
<% if request.persisted? %>
  <%= f.submit :value => "Update" %>
<% else %>
  <%= f.submit :value => "Save" %>
<% end %>

app/views/change_deadlines/_list.html.erb
<% query_options = nil unless defined?(query_options) %>
<% query_options ||= {} %>

<%= form_tag({}, :data => {:cm_url => 'requests_context_menu_path'}) do %>
  <%= hidden_field_tag 'back_url', url_for(:params => request.query_parameters), :id => nil %>
  <%= query_columns_hidden_tags(query) %>
  <div class="autoscroll">
    <table class="list issues odd-even <%= query.css_classes %>">
      <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
                            :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <% query.inline_columns.each do |column| %>
          <%= column_header(query, column, query_options) %>
        <% end %>
        <th class="buttons"></th>
        <% if User.current.allowed_to_globally?(:approve_and_reject_deadline_request) %>
          <th>Actions</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% grouped_request_list(requests, query) do |request, level, group_name, group_count, group_totals| -%>
        <% if group_name %>
          <% reset_cycle %>
          <tr style="height: 10px;" class="group open">
            <td colspan="<%= query.inline_columns.size + 2 %>">
              <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
              <span class="name"><%= group_name %></span> <span class="count"><%= group_count %></span> <span class="totals"><%= group_totals %></span>
              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                                   "toggleAllRowGroups(this)", :class => 'toggle-all') %>
            </td>
          </tr>
        <% end %>
        <% if request.status == "Approved" %>
          <tr style="background-color: #bbf7c2;" id="issue-<%= request.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
        <% elsif request.status == "Rejected" %>
          <tr style="background-color: #ffbaba;" id="issue-<%= request.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
        <% else %>
          <tr id="issue-<%= request.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
        <% end %>
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", request.id, false, :id => nil) %></td>
          <% query.inline_columns.each do |column| %>
            <%= content_tag('td', change_deadline_column_content(column, request), :class => column.css_classes) %>
          <% end %>
        <td class="buttons"><%= link_to_context_menu %></td>
        <% if request.status == "Approved" %>
          <td></td>
        <% elsif request.status == "Rejected" %>
          <td></td>
        <% else request.status == "Pending" %>
            <% if User.current.allowed_to_globally?(:edit_deadline_request, {}) %>
              <td><%= link_to l(:button_edit), edit_change_deadline_path(request)%></td>
            <% end %>
<!--            <td>-->
              <%#= link_to l(:button_approve), approve_request_path(request), style: '', :class => 'button-positive' %>
              <%#= link_to l(:button_reject), reject_request_path(request), style: 'margin-top: 5px;', :class => 'clear-link button-negative' %>
<!--            </td>-->

        <% end %>
        </tr>
        <% query.block_columns.each do |column| %>
          <% text = change_deadline_column_content(column, request) %>
          <% if text.present? -%>
            <tr class="<%= current_cycle %>">
              <td colspan="<%= query.inline_columns.size + 2 %>" class="<%= column.css_classes %>">
                <% if query.block_columns.count > 1 %>
                  <span><%= column.caption %></span>
                <% end %>
                <%= text %>
              </td>
            </tr>
          <% end -%>
        <% end -%>
      <% end -%>
      </tbody>
    </table>
  </div>
<% end %>

app/views/change_deadlines/bulk_edit.html.erb
<% @cf_setting = Setting.plugin_redmine_request_change_deadline['custom_field'] %>

<h2>Edit requests change deadline</h2>

<%= form_tag bulk_update_change_deadlines_path do %>
  <div class="autoscroll">
    <table class="list issues odd-even">
      <thead>
      <tr>
        <th>Project Name</th>
        <th>Task Name</th>
        <th>Status</th>
        <th>Subject</th>
        <th>Assignee</th>
        <th>% Done</th>
        <th>Spent time</th>
        <th>Due date</th>
        <th>Old deadline</th>
        <th>New deadline</th>
        <th>Reason</th>
      </tr>
      </thead>
      <tbody>
      <% @requests.each do |request| %>
        <tr>
          <td><%= link_to_project request.issue.project %></td>
          <td><%= link_to_issue request.issue %></td>
          <td><%= request.issue.status %></td>
          <td><%= request.issue.subject %></td>
          <td><%= request.issue.assigned_to %></td>
          <td><%= request.issue.done_ratio %></td>
          <td><%= request.issue.spent_hours %></td>
          <td><%= request.issue.due_date %></td>
          <td><%= request.old_deadline %></td>
          <td><%= date_field_tag "new_deadline[#{request.issue.id}]" %></td>
          <td><%= text_field_tag "reason[#{request.issue.id}]" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div style="padding: 10px;" class="filter-buttons">
    <%= submit_tag "Save", :class => 'icon icon-checked apply-link button-positive' %>
  </div>
<% end %>

<%#= form_for @request, url: edit_change_deadline_path do |f| %>

  <%#= render :partial => 'change_deadlines/form', :locals => {f: f, request: @request} %>
<%# end %>

app/views/change_deadlines/edit.html.erb
<% @cf_setting = Setting.plugin_redmine_request_change_deadline['custom_field'] %>

<h2>Edit request change deadline</h2>

<%= form_for @request, url: edit_change_deadline_path, method: :patch do |f| %>
  <div class="autoscroll">
    <table class="list issues odd-even">
      <thead>
      <tr>
        <th>Project Name</th>
        <th>Task Name</th>
        <th>Status</th>
        <th>Subject</th>
        <th>Assignee</th>
        <th>% Done</th>
        <th>Spent time</th>
        <th>Due date</th>
        <th>Old deadline</th>
        <th>New deadline</th>
        <th>Reason</th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to_project @request.issue.project %></td>
          <td><%= link_to_issue @request.issue %></td>
          <td><%= @request.issue.status %></td>
          <td><%= @request.issue.subject %></td>
          <td><%= @request.issue.assigned_to %></td>
          <td><%= @request.issue.done_ratio %></td>
          <td><%= @request.issue.spent_hours %></td>
          <td><%= @request.issue.due_date %></td>
          <td><%= @request.old_deadline %></td>
          <td><%= f.date_field :new_deadline %></td>
          <td><%= f.text_field :reason %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div style="padding: 10px;" class="filter-buttons">
    <%= f.submit "Save", :class => 'icon icon-checked apply-link button-positive' %>
  </div>
<% end %>

app/views/change_deadlines/new.html.erb
<% @cf_setting = Setting.plugin_redmine_request_change_deadline['custom_field'] %>

<h2><%= l('new_request') %></h2>

<%= form_for @request, url: new_change_deadline_path, method: :post do |f| %>
  <div class="autoscroll">
    <table class="list issues odd-even">
      <thead>
      <tr>
        <th>Project Name</th>
        <th>Task Name</th>
        <th>Status</th>
        <th>Subject</th>
        <th>Assignee</th>
        <th>% Done</th>
        <th>Spent time</th>
        <th>Due date</th>
        <th>Old deadline</th>
        <th>New deadline</th>
        <th>Reason</th>
      </tr>
      </thead>
      <tbody>
      <% issues = Issue.find params[:issue_ids] %>
      <% issues.each do |issue| %>
        <% cfv = issue.custom_values.detect { |cv|
          cv.custom_field_id == @cf_setting.first.to_i
        } %>
        <tr>
          <td><%= link_to_project issue.project %></td>
          <td><%= link_to_issue issue %></td>
          <td><%= issue.status %></td>
          <td><%= issue.subject %></td>
          <td><%= issue.assigned_to %></td>
          <td><%= issue.done_ratio %></td>
          <td><%= issue.spent_hours %></td>
          <td><%= issue.due_date %></td>
          <td><%= cfv %></td>
          <td><%= date_field_tag "new_deadline[#{issue.id}]" %></td>
          <td><%= text_field_tag "reason[#{issue.id}]" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div style="padding: 10px;" class="filter-buttons">
    <%= submit_tag "Save", :class => 'icon icon-checked apply-link button-positive' %>
    <%#= submit_tag "Submit", :class => 'icon icon-save save-link button', :style => "margin-left: 10px;" %>
  </div>

<% end %>

app/views/change_deadlines/show.html.erb
<h2>Request change deadline: <%= @request.id %></h2>

<ul>
  <li>Issue: <%= link_to_issue(@request.issue) %></li>
  <li>Priority: <%= @request.issue.priority %></li>
  <li>Assignee: <%= @request.issue.assigned_to %></li>
  <li>Project: <%= link_to_project(@request.project) %></li>
  <li>Request reason: <%= @request.reason %></li>
  <li>Old deadline: <%= @request.old_deadline %></li>
  <li>New deadline: <%= @request.new_deadline %></li>
  <li>Due date: <%= @request.issue.due_date %></li>
</ul>