config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

#resources :change_deadlines
#post 'change_deadlines/new', :controller => 'change_deadlines', :action => 'create'
match '/change_deadlines/context_menu', :to => 'context_menus#requests', :as => 'requests_context_menu', :via => [:get, :post]
post 'change_deadlines/new', to: 'change_deadlines#create'
patch '/change_deadlines/:id/edit', to: 'change_deadlines#update'
post '/change_deadlines/:id/approve_request', to: 'change_deadlines#approve_request', :as => 'approve_request'
get '/change_deadlines/:id/approve_request', to: 'change_deadlines#approve_request'
post '/change_deadlines/:id/reject_request', to: 'change_deadlines#reject_request', :as => 'reject_request'
get '/change_deadlines/:id/reject_request', to: 'change_deadlines#reject_request'
match '/change_deadlines', :controller => 'change_deadlines', :action => 'destroy', :via => :delete

resources :change_deadlines do
  collection do
    match 'bulk_edit', :via => [:get, :post]
    match 'approve_request', :via => [:get, :post]
    match 'reject_request', :via => [:get, :post]
    post 'bulk_update'
  end
end

app/views/context_menus/requests.html.erb
<ul>
  <% if User.current.allowed_to_globally?(:edit_deadline_request, {}) %>
    <li><%= context_menu_link l(:button_edit), bulk_edit_change_deadlines_path(:ids => @request_ids),
                              :class => 'icon icon-edit' %></li>
  <% end %>

  <% if User.current.allowed_to_globally?(:delete_deadline_request, {}) %>
    <li><%= context_menu_link l(:button_delete), change_deadlines_path(:id => @request_ids, :back_url => @back),
                              :method => :delete, :data => {:confirm => l(:text_request_destroy_confirmation)}, :class => 'icon icon-del' %></li>
  <% end %>

  <% if User.current.allowed_to_globally?(:approve_deadline_request, {}) %>
    <li><%= context_menu_link l(:approve_deadline_request), approve_request_change_deadlines_path(:ids => @request_ids),
                              :class => 'icon icon-save' %></li>
  <% end %>

  <% if User.current.allowed_to_globally?(:reject_deadline_request, {}) %>
    <li><%= context_menu_link l(:reject_deadline_request), reject_request_change_deadlines_path(:ids => @request_ids),
                              :class => 'icon icon-del' %></li>
  <% end %>
</ul>